
export const GET_RESPONSE_ERROR = "GET_RESPONSE_ERROR"
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS"
export const GET_ALL_FILMS = "GET_ALL_FILMS"
export const GET_PARTICULAR_FILM = "GET_PARTICULAR_FILM"
export const HOVER_ACTION_SUCCESS = "HOVER_ACTION_SUCCESS"
export const GET_HOVER_REQUEST = "GET_HOVER_REQUEST"